import Head from 'next/head'
import DynamicHeader from '../../components/UI/DynamicHeader'
import { getAllPageData } from '../../lib/pages'
import { getLayout } from '../../components/Layout/Layout';
import { Fragment } from 'react';
import PrivacyInfo from '../../components/Privacy/PrivacyInfo';

const Privacy = () => {
    return ( <Fragment>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/tva_logo.png" />
        </Head>
        <DynamicHeader title="Privacy Policy" description={null}/>
        <PrivacyInfo />
    </Fragment> );
}
 
const getStaticProps = async () => {
    const allPageData = getAllPageData();
    return {
        props: {
          allPageData
        } 
    }
}

Privacy.getLayout = getLayout;

export { Privacy as default, getStaticProps }