import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Authors.module.css'
import { getAllAuthorData } from '../../lib/authors'
import { getAllPageData } from '../../lib/pages'
import { getLayout } from '../../components/Layout/Layout'
import { Fragment } from 'react'


const Authors = ({ allAuthorData }) => {
    // console.log(allAuthorData)
    const authors = allAuthorData.map((author) => {
        return (
            <Link href={`/authors/${author.id}`} className={styles.gridItem} key={author.id}>
                <a>
                    <Image 
                        src={author.image}
                        alt={`${author.first_name} ${author.last_name}`}
                        width={400}
                        height={500}
                    />
                    <h2 className={styles.authorTitle}>{author.first_name} {author.last_name}</h2>
                </a>
            </Link>
        )
    })
    console.log('authors', authors)
    
    return (
        <Fragment>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/assets/tva_logo.png" />
            </Head>
            <div className={styles.gridWrapper}>
                    {authors}
            </div>
        </Fragment>
  )
}

const getStaticProps = async () => {
    const allAuthorData = getAllAuthorData();
    allAuthorData.map((author) => {
        const dateObj = new Date(author.date)
        const dateString = dateObj.toLocaleDateString("en-GB", { day: 'numeric', month: 'long', year: 'numeric' })
        author.date = dateString;
        return author;
    })
    const allPageData = getAllPageData()
    return {
        props: {
            allPageData,
            allAuthorData
        } 
    }
}

Authors.getLayout = getLayout; 
export { Authors as default, getStaticProps }