import Head from 'next/head'
import HeaderPractice from '../../components/UI/HeaderPractice'
import { getAllPageData } from '../../lib/pages'
import { getLayout } from '../../components/Layout/Layout';
import { Fragment } from 'react';

const Submissions = ({  }) => {
    return ( <Fragment>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/tva_logo.png" />
        </Head>
        <HeaderPractice title="Submissions" description={null}/>
    </Fragment> );
}

const getStaticProps = async () => {
    const allPageData = getAllPageData();
    return {
        props: {
          allPageData
        } 
    }
}

Submissions.getLayout = getLayout;

export { Submissions as default, getStaticProps }