import Head from 'next/head'
import HeaderPractice from '../../components/UI/HeaderPractice'
import { getAllPageData } from '../../lib/pages'
import { getLayout } from '../../components/Layout/Layout';
import { Fragment } from 'react';
import Guidelines from '../../components/submissions/Guidelines';
import CardTemplate from '../../components/UI/CardTemplate';
import Headshot from '../../public/images//staff_images/amberley.jpg'


const Submissions = ({  }) => {
  const cardContent = "I’m actively building my list and looking for debut commercial, reading group and literary fiction. I love beautifully crafted, evocative and original storytelling. I am also very interested in a broad range of lively and original non-fiction, particularly in the areas of narrative non-fiction, biography, memoir and cookery. I am also developing a children’s and young adult fiction list. "
    return ( <Fragment>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/tva_logo.png" />
        </Head>
        <HeaderPractice title="Submissions" description={null}/>
        <Guidelines />
        <CardTemplate header="What we're looking for..." title="Amberley Lowis" subTitle="Literary Agent" content={cardContent} image={Headshot}/>
    </Fragment> );
}

const getStaticProps = async () => {
    const allPageData = getAllPageData();
    return {
        props: {
          allPageData
        } 
    }
}

Submissions.getLayout = getLayout;

export { Submissions as default, getStaticProps }