backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "images"
collections: 
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: false
    slug: "{{title}}"
    fields: 
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Featured Image", name: "image", widget: "image"}
     - {label: "Summary", name: "summary", widget: "string"}
     - {label: "Body", name: "body", widget: "markdown"}
  - name: "author"
    label: "Author"
    folder: "_authors"
    create: true
    slug: "{{last_name}}_{{first_name}}_{{day}}{{hour}}{{minute}}"
    identifier_field: "last_name"
    media_folder: "/{{media_folder}}/author_images"
    public_folder: "/{{public_folder}}/author_images"
    fields: 
     - {label: "Date Created", name: "date", widget: "date", date_format: "DD-MM-YYYY", required: true}
     - {label: "Author ID", name: "author_id", widget: "hidden", default: "{{day}}{{hour}}{{minute}}", required: true}
     - {label: "First Name", name: "first_name", widget: "string", required: true}
     - {label: "Last Name", name: "last_name", widget: "string", required: true}
     - {label: "Website URL", name: "url", widget: "string", required: false}
     - {label: "Twitter Handle", name: "twitter", widget: "string", required: false}
     - {label: "Instagram Handle", name: "instagram", widget: "string", required: false}
     - {label: "Author's Image", name: "image", widget: "image", required: true}
     - {label: "Author's Biography", name: "body", widget: "markdown", required: true}
     - label: "Book Releases"
       name: "book_releases"
       widget: list
       create: true
       fields: 
       - {label: "Book Title", name: "book_title", widget: "relation", collection: "book", search_fields: ["title"], value_field: "{{field.slug}}", required: true}
  - name: "book"
    label: "Book"
    folder: "_books"
    create: true
    slug: "{{author_last_name}}_{{slug}}"
    media_folder: "/{{media_folder}}/book_images"
    public_folder: "/{{public_folder}}/book_images"
    fields: 
     - {label: "Date Published", name: "publish_date", widget: "date", date_format: "DD-MM-YYYY", required: true}
     - {label: "Author's First Name", name: "author_first_name", widget: "string", required: true}
     - {label: "Author's Last Name", name: "author_last_name", widget: "string", required: true}
     - {label: "Book Title", name: "title", widget: "string", required: true}
     - {label: "Book Image", name: "image", widget: "image", required: true}
     - {label: "Book Blurb", name: "body", widget: "markdown", required: false}
     - label: "Reviews"
       name: "book_reviews"
       widget: list
       required: false
       default: []
       create: true
       fields: 
       - {label: "Review Text", name: "review", widget: "string", required: true}
       - {label: "Review Written By", name: "by", widget: "string", required: true}
  - name: 'carousel'
    label: 'Carousel'
    media_folder: "/{{media_folder}}/carousel_images"
    public_folder: "/{{public_folder}}/carousel_images"
    folder: "_carousel"
    create: false
    slug: "{{images}}"
    fields: 
      - {label: "Name", name: "name", widget: "string", required: true}
      - label: "Images"
        name: images
        widget: "list"
        required: true
        create: true
        fields: 
        - { label: "Image", name: "image", widget: "image"}
     