import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getDynamicPageData } from '../lib/pages'
import { getLayout } from '../components/Layout/Layout'

const getStaticProps = async () => {
  const allPageData = getDynamicPageData();
  // const pageTitles = allPageData.map((page) => {
      
  //     return page.title;
  // })
  return {
      props: {
        allPageData
      } 
  }
}

const Home = ({ allPageData }) => {

  console.log('index', allPageData)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className={styles.title}>
          HOME PAGE
        </h1>

    </div>
  )
}

Home.getLayout = getLayout; 
export { Home as default, getStaticProps }