import Head from 'next/head'
import Image from 'next/image'
import { getAllPageData } from '../../../lib/pages'
import { getAllAuthorIDs, getAuthorData } from '../../../lib/authors'
import { getLayout } from '../../../components/Layout/Layout'
import { Fragment } from 'react'
import styles from '../../../styles/AuthorID.module.css'
import ArrowIcon from '../../../components/UI/ArrowIcon'
import { SocialIcon } from 'react-social-icons';

const Author = ({authorData}) => {
    console.log(authorData)
    const authorsName = `${authorData.first_name} ${authorData.last_name}`
    return ( <Fragment>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/tva_logo.png" />
        </Head>
        <div className={styles.authorWrapper}>
            <div className={styles.col_1}>
              <div className={styles.imageContainer}>
                <Image
                  className={styles.image}
                  src={authorData.image} 
                  alt={`${authorData.first_name} ${authorData.last_name}`}
                  layout="fill"
                  />

              </div>
            </div>
            <div  className={styles.col_2}>
              <h1 className={`${styles.headerLg} ${styles.headerBlue}`}>
                {authorsName}
              </h1>
              <h3 className={`${styles.headerSm} ${styles.headerGrey}`}>Author</h3>
              <p className={styles.text}>{authorData.markdownBody}</p>
            </div>
            <div  className={styles.col_3}>
              <h3 className={`${styles.headerSm} ${styles.headerBlue}`}>Social Links</h3>
              <ul className={styles.socialLinks}>
                {authorData.twitter && <li className={styles.listItem}><SocialIcon url="https://twitter.com" bgColor="#39778B" network="twitter" style={{ height: 40, width: 40 }}/><span className={styles.paddingLft}>{authorData.twitter}</span></li>}
                {authorData.instagram && <li className={styles.listItem}><SocialIcon url="https://instagram.com" bgColor="#39778B" network="instagram" style={{ height: 40, width: 40 }}/><span className={styles.paddingLft}>{authorData.instagram}</span></li>}
                {authorData.url && <li className={styles.listItem}><SocialIcon url="https://instagram.com" bgColor="#39778B" network="dribbble" style={{ height: 40, width: 40 }}/><span className={styles.paddingLft}>{authorData.url}</span></li>}
              </ul>
            </div>
        </div> 
        <div className={styles.bookWrapper}>
          <ArrowIcon />
        </div>
    </Fragment>
    )
}

const getStaticPaths = async () => {
    const paths = getAllAuthorIDs();
    console.log(paths)
    return {
        paths,
        fallback: false,
    };
}
const getStaticProps = async ({params}) => {
  const allPageData = getAllPageData();
  const authorData = getAuthorData(params.authorID)
  let dateObj = new Date(authorData.date)
  const uniqueID = `${dateObj.getDate()}${dateObj.getHours()}${dateObj.getMinutes()}`;
  authorData.date = uniqueID;
  // const dateString = dateObj.toLocaleDateString("en-GB")
  // authorData.date = dateString;
  console.log(authorData)
  return {
      props: {
        allPageData,
        authorData
      } 
  }
}

Author.getLayout = getLayout; 
export {Author as default, getStaticProps, getStaticPaths};