import Head from 'next/head'
import { getAllPageData } from '../../../lib/pages'
import { getAllAuthorIDs, getAuthorData } from '../../../lib/authors'
import { getLayout } from '../../../components/Layout/Layout'
import { Fragment } from 'react'


const Author = ({authorData}) => {
    console.log(authorData)
    return ( <Fragment>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/tva_logo.png" />
        </Head>
        <div>
            <h1>Author page</h1>
        </div> 
    </Fragment>
    )
}

const getStaticPaths = async () => {
    const paths = getAllAuthorIDs();
    console.log(paths)
    return {
        paths,
        fallback: false,
    };
}
const getStaticProps = async ({params}) => {
  const allPageData = getAllPageData();
  const authorData = getAuthorData(params.authorID)
  let dateObj = new Date(authorData.date)
  const uniqueID = `${dateObj.getDate()}${dateObj.getHours()}${dateObj.getMinutes()}`;
  authorData.date = uniqueID;
  // const dateString = dateObj.toLocaleDateString("en-GB")
  // authorData.date = dateString;
  console.log(authorData)
  return {
      props: {
        allPageData,
        authorData
      } 
  }
}

Author.getLayout = getLayout; 
export {Author as default, getStaticProps, getStaticPaths};